---
title: "Publications"
---

## In Press

Iyanna N, Chan EG, **Ryan JP**, Furukawa M, Coster JN, Hage CA, Sanchez PG. [Lung Transplantation Outcomes in Recipients Aged 70 years or older and
the Impact of Center Volume](https://www.mdpi.com/2077-0383/12/16/5372).  *Journal of Clinical Medicine, in press.* 

Chan EG, Pan G, Clifford S, Hyzny EJ, Furukawa M, Coster JN, **Ryan JP**, Gomez H, Sanchez PG. [Postoperative Acute Kidney Injury and Long-Term Outcomes After Lung Transplantation](https://www.annalsthoracicsurgery.org/article/S0003-4975(23)00679-3/fulltext). *Annals of Thoracic Surgery, in press* 

Hyzny EJ, Chan EG, Malik SM, Morrell MR, Furukawa M, **Ryan JP**, Sanchez PG.  [Risk Factors and Outcomes of Postoperative Hepatic Dysfunction after Lung Transplantation](https://www.annalsthoracicsurgery.org/article/S0003-4975(22)01226-7/fulltext).  *Annals of Thoracic Surgery, in press.*

Coster JN, Noda K, **Ryan JP**, Chan EG, Furukawa M, Luketich JD, Sanchez PG.  [Effects of Intraoperative Support Strategies on Endothelial Injury and Clinical Lung Transplant Outcomes](https://www.semthorcardiovascsurg.com/article/S1043-0679(23)00001-1/fulltext).  *Seminars in Thoracic and Cardiovascular Surgery, in press.*

Deitz RL, Thorngren CK, Seese LM, **s**, Ramanan R, Sanchez PG, Murray H. [Evolution of extracorporeal membrane oxygenation trigger criteria in COVID-19 acute respiratory distress syndrome](https://www.jtcvs.org/article/S0022-5223(22)01157-6/fulltext). *Journal of Thoracic and Cardiovascular Surgery, in press.*

## 2023

Mahajan A, Esper S, Oo TH, McKibben J, Garver M, Artman J, Klahre C, **Ryan JP**, Sadhasivam S, Holder-Murray J, Marroquin OC. (2023). [Development and Validation of a Machine Learning Model to Identify Patients Before Surgery at High Risk for Postoperative Adverse Events](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2807056). *JAMA Network Open,6(7)*:e2322285.

Deitz RL, Emerel L, Chan EG, **Ryan JP**, Hyzny E, Furukawa M, Sanchez PG. (2023). [Waitlist Mortality and Extracorporeal Membrane Oxygenation Bridge to Lung Transplant](https://www.annalsthoracicsurgery.org/article/S0003-4975(23)00344-2/fulltext). *Annals of Thoracic Surgery, 116(1)*: 156-162.

Furukawa M, Noda K, Chan EG, **Ryan JP**, Coster JN, Sanchez PG. (2023). [Lung transplantation from donation after circulatory death, evolution, and current status in the United States](https://onlinelibrary.wiley.com/doi/10.1111/ctr.14884). *Clinical Transplantation, 37(3)*: e14884.

Chan EG, Hyzny EJ, Furukawa M, **Ryan JP,** Subramaniam K, Morrell MR, Pilewski JM, Luketich JD, Sanchez PG. (2023).  [Intraoperative Support for Primary Bilateral Lung Transplantation: A Propensity-Matched Analysis](https://www.annalsthoracicsurgery.org/article/S0003-4975(22)00858-X/fulltext).  *The Annals of Thoracic Surgery, 115(3)*: 743-749.

## 2022

Hlavin C, Muluk S, Muluk V, **Ryan JP**, Wagner J, Dhupar R.  (2022).  [A Program to Reduce Post-Operative Opioid Prescribing at a Veteran's Affairs Hospital](A Program to Reduce Post-Operative Opioid Prescribing at a Veteran's Affairs Hospital).  *Journal of Clinical Medicine, 11(18):* 5453.

Furukawa M, Chan EG, **Ryan JP**, Hyzny EJ, Sacha LM, Coster JN, Pilewski JM, Lendermon EA, Kilaru SD, McDyer JF, Sanchez PG.  (2022).  [Induction Strategies in Lung transplantation: Alemtuzumab vs. Basiliximab a single-center experience](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9199390/).  *Frontiers in Immunology, 13:*864545.

Sanchez PG. Chan EG, Madde A, Furukawa M, Coster JN, **Ryan JP**, Luketich JD. (2022). [Transpulmonary gradient as a predictor for outcomes after lung transplantation](https://shc.amegroups.org/article/view/7184/html). *Shanghai Chest, 6(2).*

Furukawa M, Chan E, Morrell MR, **Ryan JP,** Rivosecchi R, Iasella C, Lendermon E, Pilewski J, Sanchez PG.  (2022).  [Risk factors of bronchial dehiscence after primary lung transplantation](https://onlinelibrary.wiley.com/doi/10.1111/jocs.16291).  *Journal of Cardiac Surgery, 37(4),* 950-957.

Chan EG, Hyzny EG, **Ryan JP,** Morrell MR, Pilewski J, Sanchez PG. (2022). [Outcomes Following Lung Re-transplantation in Patients with Cystic Fibrosis](https://linkinghub.elsevier.com/retrieve/pii/S1569-1993(21)02162-7).  *Journal of Cystic Fibrosis, 21(3),* 482-488.

## 2021

Joubert KD, Okusanya OT, Mazur S, **Ryan JP,** Ekeke CN, Schuchert MJ, Soloff AC, Dhupar R. (2021). [Prognostic Difference of Pleural versus Distant Metastasis after Surgery for Lung Cancer](https://www.mdpi.com/2077-0383/10/21/4846). *Journal of Clinical Medicine, 10(4846).*

Powers AA, Jones KE, Eisenberg SH, Rigatti LH, **Ryan JP,** Luketich JD, Lotze MT, LaRue AC, Dhupar R, Soloff AC. (2021).  [Experimental respiratory exposure to putative Gulf War toxins promotes persistent alveolar macrophage recruitment and pulmonary inflammation](https://www.sciencedirect.com/science/article/pii/S0024320521008262).  *Life Sciences, 282.*

Sainathan S, **Ryan JP,** Sharma M, Harano T, Morell V, Sanchez PG.  (2021). [Outcome of Bridge-to-Lung-Transplantation with ECMO in Pediatric Patients 12 Years and Older](https://www.sciencedirect.com/science/article/abs/pii/S0003497520319093).  *The Annals of Thoracic Surgery, 112(4),* 1083-1088.

Furukawa M, Chan EG, Harano T, **Ryan JP,** Rivosecchi R, Morrell MR, Sanchez PG.  (2021).  [Basiliximab versus Alemtuzumab: The Association Between Induction Agent and Airway Complications Following Lung Transplantation](https://www.frontiersin.org/articles/10.3389/fimmu.2022.864545/full).  *American Journal of Transplantation.*

Esper SA, Wallisch W, **Ryan JP,** Sanchez PG, Sciortino C, Murray H, Arlia P, D'Cunha JD, Mahajan A, Triulzi D, Subramaniam K.  (2021).  [Platelet transfusion is associated with 90‐day and 1‐year mortality for adult patients requiring veno‐arterial extracorporeal membrane oxygenation](https://onlinelibrary.wiley.com/doi/10.1111/vox.13016).  *Vox Sanguinis, 116(4),* 440-450.

Christie IG, Chan EG, **Ryan JP,** Harano T, Morrell MR, Luketich JD, Sanchez PG.  (2021).  [National trends in extended criteria donor utilization and outcomes for lung transplantation](https://www.annalsthoracicsurgery.org/article/S0003-4975(20)31123-1/fulltext).  *The Annals of Thoracic Surgery, 111(2),* 421-426.

Harano T, **Ryan JP,** Chan EG, Noda K, Morrell MR, Luketich JDL, Sanchez PG.  (2021).  [Lung transplantation for the treatment of irreversible acute respiratory distress syndrome](https://onlinelibrary.wiley.com/doi/10.1111/ctr.14182).  *Clinical Transplantation, 35(2).*

Harano T, **Ryan JP,** Morrell M, Luketich JD, Sanchez PG.  (2021).  [Extracorporeal Membrane Oxygenation for Primary Graft Dysfunction After Lung Transplantation](https://journals.lww.com/asaiojournal/Fulltext/2021/09000/Extracorporeal_Membrane_Oxygenation_for_Primary.18.aspx).  *ASAIO Journal (American Society for Artificial Internal Organs), 67(9),* 1071-1078.

Rivosecchi RM, Arakelians AR, **Ryan JP,** Murray H, Padmanabhan R, Gomez H, Phillips D, Sciortino C, Arlia P, Freeman P, Sappington D, Sanchez PG.  (2021).[Comparison of Anticoagulation Strategies in Patients Requiring Venovenous Extracorporeal Membrane Oxygenation: Heparin Versus Bivalirudin](https://journals.lww.com/ccmjournal/Abstract/2021/07000/Comparison_of_Anticoagulation_Strategies_in.12.aspx)  *Critical Care Medicine, 49(7),* 1129-1136.

Chan EG, Chan PG, Harano T, **Ryan JP,** Morrell MR, Sanchez PG.  (2021).  [Trends in lung transplantation practices across the US during the COVID-19 pandemic](https://journals.lww.com/transplantjournal/Fulltext/2021/01000/Trends_in_Lung_Transplantation_Practices_Across.28.aspx).  *Transplantation, 105(1),* 187-192.

## 2020

Jorge A, Sanchez PG, Hayanga JWA, Pilewski JM, Morrell M, Tuft M, **Ryan JP,** D'Cunha JD.  (2020).  [Routine deep vein thrombosis screening after lung transplantation: incidence and risk factors](https://www.jtcvs.org/article/S0022-5223(19)31754-4/fulltext).  *Journal of Thoracic and Cardiovascular Surgery, 159(3),* 1142-1150.

D'Cunha JD, Philips BJ, Kumar A, Burki S, **Ryan JP.**  (2020).  [Triptolide-induced apoptosis in non-small cell lung cancer via a novel miR204-5p/Caveolin-1/Akt-mediated pathway](https://www.oncotarget.com/article/27672/text/).  *Oncotarget, 11(28),* 2793-2806.

## 2018

**Ryan JP,** Karim HT, Aizenstein HA, Helbling NL, Toledo FGS.  (2018).  [Insulin sensitivity predicts brain connectivity following a meal](https://www.sciencedirect.com/science/article/abs/pii/S1053811918300247?via%3Dihub).  *NeuroImage, 171,* 268-276.

**Ryan JP,** Aizenstein HJ, Orchard TJ, Nunley KA, Karim HT, Rosano C.  (2018).  [Basal ganglia cerebral blood flow associates with psychomotor speed in adults with type 1 diabetes](https://link.springer.com/article/10.1007/s11682-017-9783-y).  *Brain Imaging and Behavior, 12(5),* 1271-1278*.*

## 2015

**Ryan JP,** Aizenstein HJ, Orchard TJ, Ryan CM, Saxton JA, Fine DF, Nunley KA, Rosano, C.  (2015).  [Age of childhood onset in type 1 diabetes and functional brain connectivity in midlife](https://journals.lww.com/psychosomaticmedicine/Abstract/2015/07000/Age_of_Childhood_Onset_in_Type_1_Diabetes_and.4.aspx).  *Psychosomatic Medicine, 77,* 622-630.

Lee JH, **Ryan J**, Andreescu C, Aizenstein HJ, Lim HK.  (2015).  [Brainstem morphological changes in Alzheimer disease](https://journals.lww.com/neuroreport/Abstract/2015/05010/Brainstem_morphological_changes_in_Alzheimer_s.5.aspx).  *NeuroReport, 26,* 411-15.

Nunley KA, Ryan CM, Orchard TJ, Aizenstein HJ, Jennings JR, **Ryan JP**, Zgibor JC, Boudreau RM, Costacou T, Maynard J, Miller RG, Rosano C.  (2015).  [White matter hyperintensities in middle-aged adults with childhood-onset type 1 diabetes](https://n.neurology.org/content/84/20/2062.long).  *Neurology, 84,* 2062-2069*.*

## 2013

Vanman EJ, **Ryan JP**, Pedersen WC, & Ito TA.  (2013).  [Probing prejudice with startle eyeblink modification: A marker of attention, emotion, or both?](https://pubmed.ncbi.nlm.nih.gov/26023325/)  *Int J Psychol Res, 6,* 30-41.

**Ryan JP**, Sheu LK, Verstynen T, Onyewuenyi IC, & Gianaros PJ.  (2013).  [Cerebral blood flow links insulin resistance and baroreflex sensitivity](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0083288).  *PLOS One, 8,* 1-8.

## 2012

**Ryan JP**, Sheu LK, Critchley HD, & Gianaros PJ.  (2012).  [A neural circuitry linking insulin resistance to depression](https://journals.lww.com/psychosomaticmedicine/Abstract/2012/06000/A_Neural_Circuitry_Linking_Insulin_Resistance_to.8.aspx).  *Psychosom Med, 74,* 476-482.

## 2011

**Ryan, JP**, Sheu, LK, & Gianaros, PJ.  (2011). [Resting State Functional Connectivity within the Cingulate Cortex Jointly Predicts Agreeableness and Stressor-Evoked Cardiovascular Reactivity](https://www.sciencedirect.com/science/article/abs/pii/S1053811910015429?via%3Dihub).   *NeuroImage, 55,* 363-370.

Parent MB, Krebs-Kraft DL, **Ryan JP**, Wilson J, & Hamann S.  (2011). [Glucose administration enhances fMRI brain activation and connectivity related to episodic memory encoding for neutral and emotional stimuli](https://linkinghub.elsevier.com/retrieve/pii/S0028-3932(11)00075-3).  *Neuropsychologia, 49,* 1052-66*.*

## 2002

Van Petten C, Luka BJ, Rubin SR, & **Ryan JP.** (2002).  [Frontal brain activity predicts individual performance in an associative memory exclusion test](https://academic.oup.com/cercor/article/12/11/1180/389993?login=false).  *Cereb Cortex, 12,* 1180-1192.
